### ISSUE TITLE
Re-license the library under LGPL

### ISSUE THREAD

**Issue by mark-stopka** [cmahon/kraken#7]
Hi,
I see this project is no longer maintained, I'd like to finish the outstanding work, however I'd prefer to license the work under LGPL, would you be open to such re-licensing?

**Comment by cmahon** [comment]
Is there a reason why you'd like LGPL specifically, or would you be happy to go with a more permissive option, such as the MIT license?

**Comment by mark-stopka** [comment]
Hi thanks for getting back to me; sure, MIT would be perhaps even better, I
just cherry-picked LGPL as we release our software under GPL class
licenses.

--
Sent from mobile
Best regards / S pozdravem,
BSc. Mark Stopka, BBA
Managing Partner @ PERLUR Group

website: www.perlur.cloud

**Comment by cmahon** [comment]
Just updated to MIT license.
